let RuleActions = dynamic([
    "AsrExecutableOfficeContentBlocked",
    "AsrExecutableOfficeContentAudited"
]);
DeviceEvents
| where Timestamp > ago(7d)
| where ActionType in (RuleActions)
| project Timestamp,
          DeviceName,
          ActionType,
          FileName,
          FolderPath,
          ProcessCommandLine,
          InitiatingProcessFileName,
          InitiatingProcessCommandLine,
          AccountName,
          AdditionalFields
| order by Timestamp desc
